"""
Lumen Light - 默认浅色主题
"""
THEME = {
    "name": "Lumen Light",
    "description": "Default light theme for Lumen",
    "colors": {
        "bg": "#f5f5f7",
        "surface": "#ffffff",
        "surfaceHover": "#f0f0f2",
        "surfaceContainer": "#f0f0f2",
        "border": "#e8e8ed",
        "text": "#1d1d1f",
        "textSecondary": "#86868b",
        "textTertiary": "#aeaeb2",
        "accent": "#2f6bff",
        "accentHover": "#2554cc",
        "danger": "#ff3b30",
        "success": "#34c759",
        "warning": "#ff9500",
        "error": "#ff3b30",
        "sidebar": "#f5f5f7",
        "sidebarHover": "#ebebf0",
        "sidebarActive": "#e0e0e5",
        "card": "#ffffff",
        "muted": "#f0f0f2",
    },
    "darkColors": {
        "bg": "#1c1c1e",
        "surface": "#2c2c2e",
        "surfaceHover": "#3a3a3c",
        "surfaceContainer": "#3a3a3c",
        "border": "#38383a",
        "text": "#f5f5f7",
        "textSecondary": "#98989d",
        "textTertiary": "#636366",
        "accent": "#4d8bff",
        "accentHover": "#6ba0ff",
        "danger": "#ff453a",
        "success": "#30d158",
        "warning": "#ff9f0a",
        "error": "#ff453a",
        "sidebar": "#1c1c1e",
        "sidebarHover": "#2c2c2e",
        "sidebarActive": "#3a3a3c",
        "card": "#2c2c2e",
        "muted": "#3a3a3c",
    },
    "fonts": {
        "heading": "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        "body": "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        "mono": "'SF Mono', 'Fira Code', monospace",
    },
    "radius": "0.625rem",
    "shadows": {
        "sm": "0 1px 2px rgba(0,0,0,0.04)",
        "md": "0 4px 6px rgba(0,0,0,0.06)",
        "lg": "0 10px 25px rgba(0,0,0,0.08)",
        "xl": "0 20px 50px rgba(0,0,0,0.12)",
        "float": "0 8px 30px rgba(0,0,0,0.12)",
    },
}
